### ISSUE TITLE
Hey! Great Project! 

### ISSUE THREAD

**Issue by akilystic** [rotem154154/self-driving-car#1]
Can you please provide steps to implement your code? How to go about it?Which files to run, etc,,

**Comment by rotem154154** [comment]
Running main.py should work using python 2.7
You will need to install all the libraries in main.py
The game will use the default model that I trained (many more in models folder)
If you want to try play yourself you can click the enter button and now you controlling the car.

**Comment by akilystic** [comment]
thanks a lot.. I'll give it a try

**Comment by paritosh3006** [comment]
does pytorch support python 2.X??
